name: design_system
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter-ExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf

    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Inter-Semibold
      fonts:
        - asset: assets/fonts/Inter-Semibold.ttf

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: Inter-Black
      fonts:
        - asset: assets/fonts/Inter-Black.ttf

    - family: Inter-Variable
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
